Improve Windows Support, Avoid Symlinks, Etc.
The repo is now designed (and documented) to be cloned directly in
`~/.unixhome`, which is no longer a symlink.

Scripts in `Setup/*` now copy (or append, as usual) snippets that load
the target files, rather than symlinking to them. This includes
`~/.emacs.d/init.el` as well as the shell startup files.

The `path` utility now returns the first argument (or `$PATH` if
omitted) even if excess arguments are seen and a non-zero exit code
thus returned, so `PATH=$(path ...)` doesn't result in an empty
`$PATH`.

Per-session profiles now support appending directories listed (one per
file) in `etc/sessions/<session-name>/cdpath_dirs/*` files. The first
non-comment, non-blank line of each such file is appended.

Per-session profiles now also support a `gopath` file that provides
(as the first non-comment, non-blank line) the value for `$GOPATH`
and, by extension, `$GOBIN`.

diff --git a/Setup/bash b/Setup/bash
--- a/Setup/bash
+++ b/Setup/bash
@@ -2,32 +2,49 @@
 
 UNIXHOME=~/.unixhome
 
-if ln --help > /dev/null 2>&1; then
-    LN=ln
+if cp --help > /dev/null 2>&1; then
+    CP=cp
 else
-    LN=gln
-    if ! $LN --help > /dev/null 2>&1; then
-        echo >&2 "ERROR: please install GNU coreutils first, so 'gln' invokes GNU 'ln'."
+    CP=gcp
+    if ! $CP --help > /dev/null 2>&1; then
+        echo >&2 "ERROR: please install GNU coreutils first, so 'gcp' invokes GNU 'cp'."
         exit 99
     fi
 fi
 
-[ "$(readlink ${UNIXHOME})" = "$(dirname $(pwd))" ] || $LN --backup=t --no-target-directory -sfv "$(dirname $(pwd))" ${UNIXHOME}
+if tail --help > /dev/null 2>&1; then
+    TAIL=tail
+else
+    TAIL=gtail
+    if ! $TAIL --help > /dev/null 2>&1; then
+        echo >&2 "ERROR: please install GNU coreutils first, so 'tail' invokes GNU 'tail'."
+        exit 99
+    fi
+fi
 
 if [ -f ~/.bashrc ]; then
-    if ! grep -qi unixhome ~/.bashrc; then
-	cat ${UNIXHOME}/etc/my-bashrc >> ~/.bashrc
+    if ! grep -qi .unixhome/etc/bashrc ~/.bashrc; then
+	$TAIL -n +3 ${UNIXHOME}/etc/my-bashrc >> ~/.bashrc  # Skip hashbang and subsequent lines.
+        echo "$0: appended my-bashrc to ~/.bashrc"
     fi
 else
-    $LN -sv ${UNIXHOME}/etc/bashrc ~/.bashrc
+    $CP -v ${UNIXHOME}/etc/bashrc ~/.bashrc
+fi
+
+if [ -f ~/.bash_profile ]; then
+    if ! grep -qi .unixhome/etc/bash_profile ~/.bash_profile; then
+        $TAIL -n +3 ${UNIXHOME}/etc/my-bash_profile >> ~/.bash_profile  # Skip hashbang and subsequent lines.
+        echo "$0: appended my-bash_profile to ~/.bash_profile"
+    fi
+else
+    $CP -v ${UNIXHOME}/etc/bash_profile ~/.bash_profile
 fi
 
 if [ -f ~/.profile ]; then
-    if ! grep -qi unixhome ~/.profile; then
-        cat ${UNIXHOME}/etc/my-profile >> ~/.profile
+    if ! grep -qi .unixhome/etc/profile ~/.profile; then
+        $TAIL -n +3 ${UNIXHOME}/etc/my-profile >> ~/.profile  # Skip hashbang and subsequent lines.
+        echo "$0: appended my-profile to ~/.profile"
     fi
 else
-    $LN -sv ${UNIXHOME}/etc/profile ~/.profile
+    $CP -v ${UNIXHOME}/etc/profile ~/.profile
 fi
-
-cmp -s ${UNIXHOME}/etc/bash_profile ~/.bash_profile || $LN --backup=t -sv ${UNIXHOME}/etc/bash_profile ~/.bash_profile
diff --git a/Setup/emacs b/Setup/emacs
--- a/Setup/emacs
+++ b/Setup/emacs
@@ -13,7 +13,23 @@ else
     fi
 fi
 
+if cp --help > /dev/null 2>&1; then
+    CP=cp
+else
+    CP=gcp
+    if ! $CP --help > /dev/null 2>&1; then
+        echo >&2 "ERROR: please install GNU coreutils first, so 'gcp' invokes GNU 'cp'."
+        exit 99
+    fi
+fi
+
 mkdir -p ~/.emacs.d
-for f in init.el; do
-    [ "$(readlink ${HOME}/.emacs.d/$f)" = "${HOME}/github/UnixHome/.emacs.d/$f" ] || $LN --backup=t -sv "${HOME}/github/UnixHome/.emacs.d/$f" "${HOME}/.emacs.d/$f"
-done
+
+if [ -f ~/.init.el ]; then
+    if ! grep -qi .unixhome/.emacs.d/init.el ~/.init.el; then
+	$TAIL -n +3 ${UNIXHOME}/.emacs.d/my-init.el >> ~/.init.el  # Skip package and subsequent lines.
+        echo "$0: appended my-init.el to ~/.init.el"
+    fi
+else
+    $CP -v ${UNIXHOME}/.emacs.d/init.el ~/.init.el
+fi
